---
title: "committees_groups"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{committees_groups}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sejm)
library(tidyr)
library(dplyr)
library(ggplot2)
library(plotly)
library(stringr)
library(glue)
```

This vignette contains the backend logic for the committees and bilateral gorup members plots In the shiny app. IT shows how to get the data from the API + all the wrangling and plotting steps needed to get the plots.

## committees

First lets load the data for committees members

```{r}
coms_members_df <- sejm::get_committees() |>
  unnest(members)
```

```{r}
#copied from the old app
waffle_df <- coms_members_df %>%
        group_by(name) %>%
        arrange(club, lastFirstName) %>%
        mutate(
          id = row_number(),        # unique ID per MP in committee
          row = (id - 1) %/% 10,    # 10 tiles per row
          col = (id - 1) %% 10,
          position = `function`,
          name = str_wrap(name, 50),
          position = replace_na(position, " ")
        ) %>%
        ungroup() 
      
      # Tooltip text
      waffle_df <- waffle_df %>%
        mutate(tooltip = glue("MP: {lastFirstName}<br>club: {club}<br>Function: {position}"))
      
      # ggplot
      p <- ggplot(waffle_df, aes(x = col, y = -row, fill = club, text = tooltip)) +
        geom_tile(color = "white", width = 0.9, height = 0.9) +
        facet_wrap(~name) +
          scale_fill_manual(values = c("PiS" = "#012b7f", "KO" = "#d41c3c", "PSL-TD" = "#3cb43c",
        "Polska2050-TD" = "#f9c300", "Lewica" = "#a81849", "Razem" = "#870f57",
        "Konfederacja" = "#1b263f", "Republikanie" = "#749cbc", "niez." = "#000000")) +
        coord_equal() +
        labs(title = "Committees and their members") +
        theme_minimal() +
        theme(
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.grid = element_blank(),
          strip.text = element_text(size= 4)
        )
      
# Convert to interactive plotly
ggplotly(p, tooltip = "text") %>%
  layout(
    hoverlabel = list(
      bgcolor = "white", 
      bordercolor = "black", 
      font = list(family = "Arial", size = 12)
    ),
    legend = list(orientation = "h", y = -0.1)
  )
```

## Bilateral groups

Get data on group members

```{r}
df_group_members <- get_bil_groups_members() |>
  rename("group_name" = "name",
         "group_id" = "id") |>
  unnest(members)
```

Make the interactive plotly

```{r}
df_group_members <- df_group_members %>%
        filter(senator == FALSE)
      
      
      waffle_df <- df_group_members %>%
        group_by(group_name) %>%
        arrange(club, name) %>%
        mutate(
          id = row_number(),        # unique ID per MP in committee
          row = (id - 1) %/% 10,    # 10 tiles per row
          col = (id - 1) %% 10,
          name = str_wrap(name, 50),
          type = replace_na(type, " ")
        ) %>%
        ungroup() 
      
      # Tooltip text
      waffle_df <- waffle_df %>%
        mutate(tooltip = glue("MP: {name}<br>club: {club}<br>Function: {type}"))
      
      # ggplot
      p <- ggplot(waffle_df, aes(x = col, y = -row, fill = club, text = tooltip)) +
        geom_tile(color = "white", width = 0.9, height = 0.9) +
        facet_wrap(~group_name) +
          scale_fill_manual(values = c("PiS" = "#012b7f", "KO" = "#d41c3c", "PSL-TD" = "#3cb43c",
        "Polska2050-TD" = "#f9c300", "Lewica" = "#a81849", "Razem" = "#870f57",
        "Konfederacja" = "#1b263f", "Republikanie" = "#749cbc", "niez." = "#000000")) +
        coord_equal() +
        labs(title = "Groups and their members") +
        theme_minimal() +
        theme(
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.grid = element_blank(),
          strip.text = element_text(size= 4)
        )
      
      # Convert to interactive plotly
      ggplotly(p, tooltip = "text") %>%
        layout(
          hoverlabel = list(
            bgcolor = "white", 
            bordercolor = "black", 
            font = list(family = "Arial", size = 12)
          ),
          legend = list(orientation = "h", y = -0.1)
        )
```

